providers = ["node"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["mkdir -p dist", "npx esbuild server.ts --bundle --platform=node --format=cjs --packages=external --sourcemap --outfile=dist/server.cjs"]

[start]
cmd = "node dist/server.cjs"
